import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomePage from "@/Components/LowScoreClubPages/HomePage";
// import { QuestionsProvider } from "@/context/QuestionContext";
import {QuestionsProvider} from "../context/QuestionContext";

// import { QuestionsProvider } from "@/context/QuestionContext";

// import { PushNotificationInit } from '@/components/PushNotificationInit'
// import { PushNotificationInit } from "@/Components/PushNotificationInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <QuestionsProvider>
        {/* <PushNotificationInit /> */}
          <HomePage>
          
            {children}
          </HomePage>
        </QuestionsProvider>

      </body>
    </html>
  );
}
